version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-sports-notification
    environment:
      - DISCORD_SECRET_TOKEN={{YOUR_VALUE}}
      - DISCORD_CHANNEL_ID={{YOUR_VALUE}}
