# https://github.com/actions/starter-workflows/blob/main/ci/docker-image.yml

name: Build a Docker image.

on:
  push:
    branches:
      - $default-branch
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.dockerignore'
      - 'Pipfile'
      - 'Pipfile.lock'
      - 'src/**'
  pull_request:
    branches:
      - $default-branch
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.dockerignore'
      - 'Pipfile'
      - 'Pipfile.lock'
      - 'src/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
